deploy/operatorsource.cr.yaml, pkg/apis/marketplace/v1alpha1/types.go, pkg/appregistry/adapter.go, pkg/appregistry/appregistry.go, pkg/appregistry/appregistry_test.go, pkg/appregistry/client.go, pkg/appregistry/mock_adapter.go, pkg/operatorsource/reconciler.go
For an `OperatorSource` type, allow the admin to specify a registry namespace to filter by
=> Filter by registry namespace

deploy/examples/catalogsourceconfig.cr.yaml, deploy/examples/operatorsource.cr.yaml
I noticed that the marketplace operator expects CatalogSourceConfig CRs to specify the field "metadata.namespace" with the namespace that created it.
=> CatalogSourceConfig requires field "metadata.namespace"

pkg/datastore/datastore_test.go
Use assert.ElementsMatch to compare the lists instead of
assert.EqualValues which compares objects.
=> [tests] Fix datastore unit test case

Gopkg.lock, pkg/catalogsourceconfig/configuring.go, pkg/datastore/datastore.go, pkg/datastore/datastore_test.go, pkg/datastore/manifest.go, pkg/datastore/metadata.go, pkg/datastore/mock_unmarshaler.go, pkg/datastore/unmarshaler.go, pkg/datastore/unmarshaler_test.go
When datastore combines multiple manifest(s) into one, it yields malformatted YAML. This renders the associated ConfigMap and CatalogSource objects unusable as OLM throws a parsing error when
it tries to load the manifest from the ConfigMap. 
The reason "combine" operation yields malformatted YAML is because it concatenates string representation of OLM object(s) while combining multiple manifest(s). In order to resolve this issue,
we need to do the following:
- Implement more structured unmarshaling of manifest YAML document(s) so that we can break a manifest down into a set of CRD, CSV and package object(s).
- When we combine multiple manifest(s) we merge array(s) of OLM object(s) instead of string concatenation.
=> Fix yaml parsing error

pkg/apis/marketplace/v1alpha1/operatorsource_types.go, pkg/datastore/datastore.go, pkg/datastore/datastore_test.go, pkg/datastore/testdata/source-1.yaml, pkg/datastore/testdata/source-2.yaml, pkg/operatorsource/downloading.go, pkg/operatorsource/downloading_test.go, pkg/operatorsource/factory.go, pkg/operatorsource/handler.go, pkg/operatorsource/updated.go, pkg/operatorsource/updated_test.go, pkg/operatorsource/validating.go
When an admin updates the spec of an OperatorSource object we need to reconcile so that the new spec takes effect.
What needs to be done:
* Save OperatorSource spec to datastore. 
* Determine if the Spec has been changed, we will consider change in spec as an update event.
* Reconcile update event appropriately.
=> Reconcile OperatorSource Spec update

pkg/catalogsourceconfig/cache.go, pkg/catalogsourceconfig/cache_test.go, pkg/catalogsourceconfig/catalogsourcebuilder.go, pkg/catalogsourceconfig/configmapbuilder.go, pkg/catalogsourceconfig/configuring.go, pkg/catalogsourceconfig/factory.go, pkg/catalogsourceconfig/handler.go, pkg/catalogsourceconfig/update.go, pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go, pkg/controller/operatorsource/operatorsource_controller.go, pkg/operatorsource/handler.go
- Introduce an in-memory CatalogSourceConfig UID : Spec
This cache is used to detect when a CR needs to be updated. Note that
this cache is a temporary construct which will be removed when we move
to using the Operator Registry as the data store for CatalogSources.
- Introduce a new Update reconciler
This reconciler sets the phase back to "Configuring" allowing the
ConfigMap and CatalogSource to be updated or deleted and recreated
depending on whether the target namespace changed. The "Configuring"
reconciler has been updated to detect if the respective object is
already present and to create or update it depending on that.
- Replace default controller client with a non-default one
Now that we need to query other namespaces for ConfigMaps and
CatalogSources, we no longer can use the …
=> Handle CatalogSourceConfig updates

deploy/marketplace.csv.yaml
This bug came as a result of the changes that were introduced when the project was rebuilt using version 0.1.1 of the operator sdk.
In this update, the service account changed from default to marketplace-operator. The csv has been updated to use the marketplace-operator service account.
=> [bug] Update csv to use the expected service account and namespace

Dockerfile
Root Dockerfile currently uses ocp builder image
Use openshift/release image instead
=> Update upstream Dockerfile

cmd/manager/main.go, deploy/marketplace.csv.yaml, deploy/operator.yaml
Updated main.go to include an http endpoint that returns a 200 status when pinged for use in readiness and liveness probes.
Updated the operator.yaml to include a readiness and liveness probe.
=> [deploy] Add liveness and readiness probes

pkg/apis/marketplace/v1alpha1/operatorsource_types.go, pkg/datastore/datastore.go, pkg/operatorsource/downloading.go, pkg/operatorsource/downloading_test.go
Add a new field called 'Packages' to OperatorSourceStatus. This is a
comma separated list of operator manifest(s) downloaded by
marketplace operator from the registry specified by the OperatorSource
object.
When an OperatorSource object is reconciled this field allows us to see
the list of manifest(s) processed.
=> [opsrc] Add downloaded manifest list to Status

.gitignore
Update .gitignore based on output from https://www.gitignore.io/api/go,vim,emacs,visualstudiocode,jetbrains
=> Update .gitignore to include Jetbrain IDEs

README.md, deploy/crds/catalogsourceconfig.crd.yaml, deploy/crds/operatorsource.crd.yaml, deploy/examples/catalogsourceconfig.cr.yaml, deploy/examples/operatorsource.cr.yaml, deploy/marketplace.ns.yaml, deploy/marketplace.v0.0.1.clusterserviceversion.yaml, deploy/operator.yaml, deploy/role_binding.yaml, scripts/e2e-tests.sh
The changes introduced in this PR:
* Rename the marketplace csv so the OLM provided `make release` command includes Marketplace in it's configMap.
* Clearly shows that the latest marketplace image is used
* Removes incorrect x-descriptorsi
* Update the operators display name
* Updates the Readme to reflect these changes
=> [deploy] Update the marketplace csv for use with OLM.

pkg/catalogsourceconfig/catalogsourcebuilder.go, pkg/catalogsourceconfig/configuring.go, pkg/operatorsource/catalogsourceconfigbuilder.go, pkg/operatorsource/helper_test.go
- Update the CatalogSourceConfigBuilder` to add a datastore label.
- The CatalogSourceConfig's configuring reconciler will check for this datastore label. If present it will add the _olm-visibility: hidden_ and _openshift-marketplace: true_ labels to the CatalogSource. 
_olm-visibility: hidden_ will cause the CatalogSource to be hidden in the OLM Package Manifest UI. 
_openshift-marketplace: true_ will be used to filter out the global CatalogSources in the Marketplace UI.
- Add the datastore label to the ObjectMeta in helperNewCatalogSourceConfig()
=> [csc+opsrc] Introduce datastore label

pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go, pkg/catalogsourceconfig/configuring.go, pkg/catalogsourceconfig/update.go, pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/purging.go, pkg/operatorsource/purging_test.go, test/e2e/marketplace_test.go
- Remove the prefixes of the created CatalogSourceConfigs, CatalogSources and ConfigMaps. This has been done to make the naming more consistent.
- Hard code the display name to "Marketplace Operators" and publisher to "Red Hat" in the CatalogSource. This has been done to make the OLM package UI display look nice.
=> Improve naming of CRs

pkg/datastore/datastore.go, pkg/datastore/metadata.go, pkg/datastore/row.go, pkg/operatorsource/outofsync.go
* Make `datastore` access concurrent since there will be concurrent reader(s) and writer(s) of the underlying datastore.
* Store registry metadata that includes release information associated with each repository in remote registry so that we can determine if there is a new release.
* Add a new function 'OperatorSourceHasUpdate' that returns true if the operator source in remote registry has any update(s).
The above feature(s) are going to pave the way for `sync in cluster datastore cache with remote registry update(s)`.
=> Make datastore access concurrent

pkg/apis/marketplace/v1alpha1/operatorsource_types.go, pkg/operatorsource/deleted.go, pkg/operatorsource/factory.go, pkg/operatorsource/initial.go
-Add deletedReconciler to opsrc reconcilers
-Use finalizer to reconcile before deleting opsrc
-Delete manifests from cache when deleting
=> [opsrc] Handle OperatorSource deletion

pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go
- The list of package(s) specified in `Spec.Packages` of the `CatalogSourceConfig` should include the package(s) from the associated `OperatorSource` only.
=> [opsrc] support for multiple operator source CR(s)

cmd/manager/main.go, pkg/appregistry/client.go, pkg/datastore/datastore.go, pkg/datastore/row.go, pkg/operatorsource/poller.go, pkg/operatorsource/pollhelper.go, pkg/operatorsource/syncer.go
Keep in-memory OperatorSource cache of datastore in sync with remote registry update(s). Rebuild the local cache when any of the following happens:
- A new repository has been added to the given namespace in remote registry associated with the OperatorSource object.
- An existing repository has been removed from the given namespace in remote registry associate with the OperatorSource object.
- A new release has been pushed for an existing repository in remote registry associate with the OperatorSource object.
Implement the following to accomplish the above goal:
* Add a new function 'ListPackages' in appregistry that returns latest metadata (with release information) for all repositories under the given namespace.
* Add 'Poller' that polls for changes to the underlying namespace …
=> Keep datastore in sync with registry update(s)

pkg/catalogsourceconfig/configuring.go
-Reorder imports in /pkg/catalogsourceconfig/configuring.go to standard
=> Format configuring.go imports correctly

pkg/catalogsourceconfig/catalogsourcebuilder.go, pkg/catalogsourceconfig/configuring.go, pkg/operatorsource/catalogsourceconfigbuilder.go, pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/helper_test.go, pkg/operatorsource/purging.go, test/e2e/marketplace_test.go
Allow the admin to filter operator offering(s) by Operator Type.
With multiple operator source(s) an admin needs the ability to filter
operator offering(s) by group. For example, we want to list operator
offering(s) from "Community" or "ISV" etc.
Make the following change(s) to achieve this goal:
- Apply all label(s) associated with an OperatorSource to its
corresponding CatalogSourceConfig object.
This will ensure that the corresponding CatalogSource object
has all the label(s) from the OperatorSource object.
This will cause Package API server to return the same label(s) for
all PackageManifest object(s) related to the CatalogSource
in question.
We can use a specific label `opsrc-group` that reflects the group
name of an operator source. The UI can utilize this label to
filter operator …
=> [opsrc] Add support to filter operator offering(s)

pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go
Make configuring reconciler for OperatorSource object idempotent.
Right now, if the given CatalogSourceConfig object already exists
then the reconciler assumes that it is already properly configured
and moves on. This may not be true, due to unexpected error we might
have stale CatalogSourceConfig object. Making the configuring
reconciler idempotent helps us work around these issue(s).
Do the following to make it idempotent:
- Call Create to cretae the CatalogSourceConfig object.
- If we get an AlreadyExists error, then get the latest version
of the object.
- Set the fields appropriately and then Call Update.
=> [opsrc] Make configuring reconciler idempotent

pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/downloading.go, pkg/operatorsource/purging.go, pkg/operatorsource/validating.go
On any reconciliation error we set the current phase to 'Failed'. The reconciliation of a Failed OperatorSource object is currently a no op. In order to retry a failed reconciliation, do the following:
- On error, make sure the object retains its current phase so that the next retry can resume from the current phase.
- Set 'CurrentPhase.Message' to the last error encountered so that  the object reflects the most recent error encountered.
=> [opsrc] Add retry logic to opsrc reconciliation

deploy/marketplace.v0.0.1.clusterserviceversion.yaml, deploy/operator.yaml, manifests/10_operator.yaml
As per CVO guidelines, all the operators it manages must be deployed to the master node. The toleration is added to allow the pod onto any node with any taint.
=> [deploy] Deploy operator to master node

pkg/catalogsourceconfig/configuring.go, pkg/catalogsourceconfig/update.go
On any reconciliation error we set the current phase to 'Failed'. The reconciliation of a Failed CatalogSourceConfig object is currently a no op. In order to retry a failed reconciliation, do the following:
- On error, make sure the object retains its current phase so that the next retry can resume from the current phase.
- Set 'CurrentPhase.Message' to the last error encountered so that the object reflects the most recent error encountered.
=> [csc] Add retry logic to csc reconciliation

cmd/manager/main.go, pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go, pkg/catalogsourceconfig/syncer.go, pkg/catalogsourceconfig/triggerer.go, pkg/datastore/datastore.go, pkg/datastore/metadata.go, pkg/datastore/row.go, pkg/datastore/update_result.go, pkg/operatorsource/poller.go, pkg/operatorsource/pollhelper.go, pkg/operatorsource/syncer.go
When a new version of an operator is pushed to quay.io, we want to
make the new version available to existing CatalogSource object(s)
so that user can upgrade to the new version.
Make the following change(s) to achieve this goal:
- Extend datastore to maintain a list of package(s) associated with
each repository so that when a repository has a new version we
can relate to the package(s)involved.
- Extend datastore to return more fine grained information on update:
-- Return a list of repositories that have new versions.
-- Return a list of repositories that have been removed
from the registry namespace.
- Implement a sync loop that waits on a channel for package update
notification. Once activated, it lists all existing
CatalogSourceConfig object(s) [label: opsrc-datastore!=true]. for …
=> Update catalog when a new version is available

pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go, pkg/operatorsource/configuring.go
OperatorSource reconciler fails in 'Configuring' phase if the
following conditions are true:
- The CatalogSourceConfig object already exists.
- It is already owned by the OperatorSource object.
The reconciler appends the OperatorSource object to the
OwnerReference list of the CatalogSourceConfig without checking
whether it is already owned by the same OperatorSource. This causes
the Update API to throw an error.
Solution: Remove the given OperatorSource object from the
OwnerReference list to ensure it is not specified more than once.
Bugzilla link: https://bugzilla.redhat.com/show_bug.cgi?id=1672701.
=> [opsrc] Fix OperatorSource reconciliation error

pkg/operatorsource/configuring.go, pkg/operatorsource/purging.go, pkg/operatorsource/purging_test.go
On restart, marketplace operator deletes and recreates the
CatalogSourceConfig object(s) associated with each OperatorSource.
These are CatalogSourceConfig object(s) having the following label:
opsrc-datastore: "true"
Resolution:
- Do not delete CatalogSourceConfig object(s) during purge, instead
let the CatalogSourceConfig(s) be updated during the reconciliation
process  ( in configuring phase ).
- Make the log a bit clearer by mentioning whether it is creating
or updating a CatalogSource object in 'Configuring' phase.
https://jira.coreos.com/browse/MKTPLC-236
https://bugzilla.redhat.com/show_bug.cgi?id=1682928
=> [opsrc] Do not delete csc during purge

manifests/05_role.yaml, pkg/catalogsourceconfig/catalogsourcebuilder.go, pkg/catalogsourceconfig/configuring.go, pkg/catalogsourceconfig/deleted.go, pkg/catalogsourceconfig/deploymentbuilder.go, pkg/catalogsourceconfig/podtemplatebuilder.go, pkg/catalogsourceconfig/registry.go, pkg/catalogsourceconfig/rolebindingbuilder.go, pkg/catalogsourceconfig/rolebuilder.go, pkg/catalogsourceconfig/serviceaccountbuilder.go, pkg/catalogsourceconfig/servicebuilder.go, pkg/operatorsource/catalogsourceconfigbuilder.go, pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/deleted.go
-Since owner references across namespaces are unreliable, remove them
-Stop adding owner references to created resources
-Track resources that need to be deleted with labels
-Delete all created resources in finalizer of respective custom resource
=> Remove Dependency on Owner References

pkg/catalogsourceconfig/cache.go, pkg/operatorsource/configuring.go, pkg/operatorsource/syncer.go
**Problem**
Prior to f9d37cc029, as part of syncing `OperatorSources`, the associated `CatalogSourceConfigs` were being deleted and recreated. This always ensured that we got the latest state from Quay. With that change we moved to updating `CatalogSourceConfigs`. Now in the scenario where a Quay namespace has changed without app-registry repositories being added or removed but with existing repositories being updated, these updates will not be reflected on the cluster.
**Solution**
The right fix for this would be for the `CatalogSourceConfig` cache to become app-registry version aware and to detect that updates are required not just based on spec changes. In the short term an easy fix is to drop the `CatalogSourceConfig` status before updating.
This fixes [bug …
=> Bug 1685066: Fix OperatorSource sync

pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go, pkg/catalogsourceconfig/cache.go, pkg/catalogsourceconfig/cache_test.go, pkg/catalogsourceconfig/configuring.go, pkg/catalogsourceconfig/registry.go
A CatalogSourceConfig spec should allow a valid set of packages to be specified with spaces in between them. For example: foo, bar, jazz
=> Bug 1680070: Allow specifying spaces in between packages

deploy/operator.yaml, manifests/10_operator.yaml
- Specify `system-cluster-critical` priority for operator
- Blocks passing smoke tests for ensuring control plane pods always schedule
See: openshift/origin#22217
Fixes [bug 1685331](https://bugzilla.redhat.com/show_bug.cgi?id=1685331)
=> Bug 1685331: Update priority for operator

deploy/crds/catalogsourceconfig.crd.yaml, deploy/upstream/02_catalogsourceconfig.crd.yaml, manifests/02_catalogsourceconfig.crd.yaml
- Fixes #116
- Removed `TARGETNAMESPACE`, `PACKAGES`, `DISPLAYNAME` and `PUBLISHER` fields from output
- Modified catalogsourceconfig.crd to remove fields from `additionalPrinterColumns`
=> Bug 1683422: [csc] Make CLI output less verbose

deploy/role.yaml, deploy/role_binding.yaml, deploy/upstream/05_role.yaml, deploy/upstream/06_role_binding.yaml, manifests/05_role.yaml, manifests/06_role_binding.yaml
After moving to using grpc CatalogSources, the operator is dealing with more resources like `Services` and `Deployments`. Initially there were being created in a different namespace that required a `ClusterRole`. But the final implementation saw the resources being created in the same namespace. Given that we create a `Role` and `RoleBinding` for those resources we are dealing with in our namespace. The only resources we need a ClusterRole for are `CustomResourceDefinitions`, `ClusterOperator` and `CatalogSources`.
This fixes [bug 1685647](https://bugzilla.redhat.com/show_bug.cgi?id=1685647)
=> Bug 1685647: Remove unnecessary ClusterRoles

Makefile, cmd/manager/main.go, pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go, pkg/catalogsourceconfig/configuring.go, pkg/catalogsourceconfig/syncer.go, pkg/catalogsourceconfig/triggerer.go, pkg/datastore/datastore.go, pkg/datastore/update_result.go, pkg/operatorsource/downloading.go, pkg/operatorsource/downloading_test.go, pkg/operatorsource/factory.go, pkg/operatorsource/handler.go, pkg/operatorsource/poller.go, pkg/operatorsource/syncer.go
Currently, the opsrc poller will update the package list and send a
notification to the catalog syncer if there are changes to any of its
packages. This has several limitations however, primarily that if there
is any service hiccup or an opsrc is deleted, the history of upgrade is
lost. To alleviate that issue, the following has been updated:
- Added a PackageMap to the status of catalogsourceconfig. This is a
mapping between PackageName and current version at the time the
catalogsourceconfig was created.
- Modified the catalogsyncer to include a new method,
SyncRefresh() that pushes an empty notification onto the listening
channel and calls the Trigger()
- Modified the trigger method so that, when this empty notification is
sent, the triggerer will compare all non-datastore …
=> Bug 1679284: Properly sync catalogsourceconfigs

build/Dockerfile
Problem:
Using the operator-sdk build command is currently broken on this project
The operator-sdk expects a dockerfile in the path `build/Dockerfile`
to build the container image
Currently, that Dockerfile refers to a source binary that is incorrectly
named
Solution:
Update the dockerfile to point to the correct binary:
`marketplace-operator`
=> Fix Operator-SDK build

pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
Problem:
When adding catalogsourceconfig.status.PackageRepositioryVersions to
the schema of CatalogSourceConfig, the json field was defined improperly
Solution:
Update the `status.PackageRepositoryVersion` json string name from
`packageMap` to `packageRepositioryVersions`
This should have been included as part of the fix for:
https://bugzilla.redhat.com/show_bug.cgi?id=1679284
=> Bug 1679284: [csc] Fix PackageRepositoryVersions json string

pkg/catalogsourceconfig/deleted.go, pkg/catalogsourceconfig/handler.go, pkg/operatorsource/deleted.go, pkg/operatorsource/handler.go
Problem:
This recent change
(https://github.com/operator-framework/operator-marketplace/pull/127)
introduced a reduced scope to our cluster role. However, when deleting
`CatalogSourceConfigs` the current implementation of the delete
reconciler still required the cluster roles that were removed.
Because of this, the reconciler was producing an error and prevented the
`csc` from being deleted. Additionally, the operator was panicking
because the transitioner logic expected an object to return in that case
Solution:
Update the `deleteCreatedResources` method in the `deletedReconciler` to
use a namespace option when getting the lists of services, deployments,
rolebindings, roles and service accounts.
Update the`Reconcile` method in both the csc's and the opsrc's
`deletedReconciler` to always …
=> Bug 1688703: Properly handle delete failures

pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go, pkg/catalogsourceconfig/cache.go, pkg/catalogsourceconfig/registry.go
Problem:
In some cases, when the Openshift UI updates the package list of a csc
after removing a subscription, the update does not properly format the
package list. For example:
`packages: ',strimzi-kafka-operator-test'`
In this example, the package list accidentally includes a leading comma.
Right now, the marketplace doesn't handle poorly formatted package
lists in the csc spec. In general, if a user accidentally leaves a comma
behind the operator should ignore it and proceed as normal with the
list of valid packages.
Solution:
Any time the operator reads the package list, that read happens
from a public method that formats the package list and excludes invalid
packages (specifically empty string).
Added a private method `getValidPackageSliceFromString()` that takes a
package string and …
=> Bug 1686668: [csc] Ignore invalid values when reading `csc.Spec.Packages`

cmd/manager/main.go, deploy/role.yaml, deploy/upstream/05_role.yaml, manifests/05_role.yaml, manifests/11_clusteroperator.yaml, pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go, pkg/controller/operatorsource/operatorsource_controller.go, pkg/status/status.go, pkg/status/syncratio.go, pkg/status/syncutils.go
Cluster operators are expected to report the version of the payload
they are included in once they are "deployed", and also to keep the
cluster operator object created. With this update the marketplace
operator will keep CO up to date, report the payload version once it
hits available, and use the count of successful syncs as a
probalistic measurement of "available".
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1686121
=> Bug 1686121 & 1689443: Update management of clusterOperator

pkg/catalogsourceconfig/cache.go, pkg/catalogsourceconfig/factory.go
Problem:
Rebuilding the `CatalogSourceConfig` state relies on the cache
implementation. Currently, if the spec is updated on a csc it will
not automatically attempt to reconcile that change. Instead, the phase
factory checks if the spec has been updated from the previous update.
To accomplish this, it checks an in-memory cache that compares the
cached spec to the current spec. This is troublesome in the case where
the `marketplace` restarts, because the in memory cache is lost. This
bug is caused when an existing `catalogsourceconfig` gets an update:
the cache is empty for that `csc` but we do not return stale.
Resolution:
Update the `IsEntryStale` method on the `csc` cache. In all cases, if
the `csc` is not found in the cache we should return stale.
Also update `GetPhaseReconciler` to …
=> Bug 1691241: [csc] Don't ignore cache on restart

README.md
- Changed CRD descriptions from paragraph to bullet form
- Added link to authenticated-private-repo doc in
Populating AppRegistry section
The README has a lot of information in it, and it's hard for users
to find the information they're looking for.
The Description section has useful info and links, which were
difficult to see or find while it was in paragraph form.
I've added a redundant link to the private AppRegistry repository
doc in the Populating AppRegistry section since this it is related
to that section.
=> [docs] Reorganize README to make it easier to read

test/testsuites/csctargetnamespacetests.go
csc kind was set to operatorsource kind in the targetNamespace e2e tests. The kind gets overwritten by the createRuntimeObject function and that's why this error wasn't caught at runtime. This PR fixes the kind to ensure that no runtime error gets produced in the future.
=> [e2e] fix wrong csc kind

test/helpers/helpers.go, test/testgroups/operatorsourcetests.go, test/testsuites/csctargetnamespacetests.go, test/testsuites/opsrccreationtests.go
Extended the targetNamespace testsuite to check that a CatalogSourceConfig
with different namespace and targetNamespace values is properly deployed
and cleaned up.
Other notes:
* Updates CSC packages to pull package from marketplace_e2e operator source.
* Add new functions to helpers package
=> [e2e] Add CSC test where namespace != targetNamespace

deploy/marketplace.ns.yaml, manifests/01_namespace.yaml
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
=> Add node-selector annotation to namespace

pkg/status/status.go, pkg/status/syncratio.go, pkg/status/syncutils.go
Problem:
When the marketplace-operator starts up, it starts a cluster status monitoring
routine. In some cases, the marketplace-operator will incorrectly mark the
status as failing when a large enough number of operands fail to reconcile
successfully (for example, OperatorSources that are pointing to an invalid
app registry path).
Solution:
Update marketplace-operator to report availability based on whether or not it
is able to reconcile CatalogSourceConfigs and OperatorSources. Report failing
if OperatorSources or CatalogSourceConfigs fall below golden ratio, but keep
available condition set to true.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1700416
=> Bug 1700416:[status] Fix Status Reporting

test/e2e/main_test.go, test/testgroups/nosetuptests.go, test/testsuites/invalidopsrctests.go
- Creates NoSetupTestGroup for tests that don't require any
resources upfront
- Testsuite for invalid OperatorSource tests
- Check for OperatorSource with invalid URL
- Check for OperatorSource with invalid endpoint
- Check for OperatorSource with non-existent regsitry namespace
These OperatorSource tests each create an invalid OperatorSource
and check that the status reaches the appropriate failed state.
=> [e2e] Add tests for invalid OperatorSources

scripts/e2e-tests.sh
Feeding `--go-test-flags -v` flag to `operator-sdk test` command
to make output of e2e tests more verbose.
=> [e2e] Make CLI output for tests more verbose

test/helpers/helpers.go, test/testgroups/nosetuptests.go, test/testsuites/opsrcdeletetests.go
-Added an e2e test which confirms that if an operator source is deleted
the resulting resources are deleted as well
-Added a helper function to create a resource without cleanup options
=> [e2e] Add opsrc delete test

docs/troubleshooting.md
Extend troubleshooting.md to describe how the marketplace operator handles
conflicting package names.
=> [docs] Document Conflicting Package Name Behavior

deploy/operator.yaml, manifests/10_operator.yaml
In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …
=> Fix tolerations

cmd/manager/main.go, pkg/status/status.go
Problem:
When the marketplace operator is stopped and restarted, it should not
implicitly mark the ClusterOperator status as degrading.
Solution:
When the Operator exits, simply log that the operator has exited and exit
gracefully.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1706867
=> Bug 1706867: ClusterOperator degrading on exit

pkg/catalogsourceconfig/handler.go, pkg/operatorsource/handler.go
If a user edits an OperatorSource with validation off and sets a
required attribute to an invalid value then marketplace operator runs
into update error when it tries to reconcile the object.
We don't currently log the update error from within the handler. Add
logging to both OperatorSource and CatalogSourceConfig handler to log
the update error during reconciliation error.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1693964
Jira: https://jira.coreos.com/browse/MKTPLC-329
=> Bug 1693964: Log reconciliation update error

test/helpers/helpers.go, test/testgroups/operatorsourcetests.go, test/testsuites/const.go, test/testsuites/cscpackagetests.go, test/testsuites/csctargetnamespacetests.go, test/testsuites/opsrccreationtests.go, test/testsuites/opsrcdeletetests.go
Adds e2e test to check that a csc with a non-existent package fails
properly and does not create child resources
=> [e2e] csc with non-existent package

cmd/manager/main.go, pkg/status/status.go, pkg/status/syncratio.go
Fix small errors in comment and rename `cluster operator` to `ClusterOperator`.
=> [status] Reformat status comments

deploy/crds/operators_v1_catalogsourceconfig_crd.yaml, deploy/crds/operators_v1_operatorsource_crd.yaml, deploy/upstream/02_catalogsourceconfig.crd.yaml, deploy/upstream/03_operatorsource.crd.yaml, manifests/02_catalogsourceconfig.crd.yaml, manifests/03_operatorsource.crd.yaml
Problem:
The CatalogSourceConfig and OperatorSource Custom Resource Definitions
(CRD) are missing the openapi definition fields.
Solution:
Update the CRDs with the `spec.validation.openAPIV3Schema.description`
field.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1708503
=> Bug 1708503: Fix missing openapi CRD descriptions

Makefile, pkg/client/client.go, pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/downloading_test.go, pkg/operatorsource/handler_test.go, pkg/operatorsource/helper_test.go, pkg/operatorsource/purging_test.go
- Refractor OperatorSource configuring reconciler
- Introduce CatalogSourceConfigCrud for OperatorSource configuring reconciler
- Include tests for CatalogSourceConfigCrud
- Update OperatorSource tests with fake client
- Remove kubeclient mocks from generate-mocks target in Makefile
=> Migrate to fake client for OperatorSource unit tests

pkg/status/status.go
Problem: If the marketplace operator is started in a container where the RELEASE_VERSION environment variable is not set, the ClusterOperator version will be set to an empty string.
Solution: If the RELEASE_VERSION is not set, warn the user by setting the ClusterOperator version to "OpenShift Independant Version".
=> [status] Handle unset RELEASE_VERSION env var

test/e2e/main_test.go, test/testgroups/clusteroperatortests.go, test/testsuites/clusteroperatorstatustests.go
This test checks each of the ClusterOperator Conditions in its Status and
ensures that these match the expected Conditions when the marketplace operator
is available and healthy.
=> [e2e] Check ClusterOperator Status upon initialization

CONTRIBUTING.md
The command to delete the marketplace deployment is wrong.
This PR fixes the command.
=> [doc] Fix command to delete deployment

docs/troubleshooting.md
Some link addresses were changed due to PR #176 but the links
were not updated. This PR fixes the broken links with the
correct link addresses.
=> [doc] Fix broken links in troubleshooting doc

test/helpers/helpers.go, test/testgroups/operatorsourcetests.go, test/testsuites/opsrcdeletetests.go, test/testsuites/packagestests.go
Introduce a test that ensures that an OperatorSource and its child resources
are successfully rolled out regardless of whether or not there is a
package conflict with an exiting OperatorSource.
=> [e2e] OperatorSource with conflicting packages

Makefile, scripts/e2e-tests.sh, test/e2e/main_test.go
- Add a new Makefile target for minikube
- Update e2e-tests.sh to accept an argument that will decide which namespace the marketplace operator is running in
- Only run the ClusterOperator test if the API can be added to the scheme
=> [e2e] Enable tests to run against minikube

test/helpers/helpers.go, test/testsuites/invalidopsrctests.go
Add a helper function that waits for an OperatorSource to be created and reach the expected phase and message.
=> [e2e] Modularize waiting for opsrc creation

README.md, deploy/crds/operators_v2_catalogsourceconfig_crd.yaml, deploy/examples/catalogsourceconfig.cr.yaml, deploy/upstream/02_catalogsourceconfig.crd.yaml, docs/csc-source-resolution.md, manifests/02_catalogsourceconfig.crd.yaml, pkg/apis/operators/v2/catalogsourceconfig_types.go, pkg/catalogsourceconfig/cache.go, pkg/catalogsourceconfig/configuring.go, pkg/catalogsourceconfig/syncer.go, pkg/catalogsourceconfig/triggerer.go, pkg/datastore/datastore.go, pkg/datastore/datastore_test.go, pkg/datastore/metadata.go, pkg/datastore/update_result.go, pkg/grpccatalog/grpccatalog.go, pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/poller.go, pkg/operatorsource/syncer.go, pkg/registry/registry.go, test/testsuites/packagestests.go
This changes introduces logic that allows CSCs to specify a specific
OpSrc to pull the packages from::
* If a source is not specified in a CSC, marketplace will attempt to
identify an OpSrc that contains all packages and will update the
spec.source of the CSC to point to the OpSrc. If an appropriate
OpSrc is not found, or if multiple OpSrcs could be selected,
the CSC will be moved to the Configuring phase and alert the user.
* If a source is specified in a CSC but does not exist, the CSC will
be moved to the Configuring phase and alert the user.
* If a source is specified but that OpSrc is missing packages, the
CSC will be moved to the Configuring phase and alert the user about
the missing packages.
* If a source is specified and contains all packages, the CSC will be
reconciled …
=> [csc] Update CSC to specify a source name

test/e2e/main_test.go
Change the name of the variable that indicates the ClusterOperator API is available on cluster to reflect it's usage.
=> [e2e] Fix variable name

pkg/status/status.go, test/testsuites/clusteroperatorstatustests.go
**Problem:**
The must-gather tool is not able to gather enough information about the marketplace operator.
**Solution:**
The must-gather tool requires a field, RelatedObjects, in the ClusterOperator CR to be populated with ObjectReferences of the resources associated with the operator. This PR populates this field with the operator's namespace and the default OperatorSource/CatalogSourceConfig/CatalogSource resources.
=> Bug 1717439: [status] Populate RelatedObjects

pkg/builders/builders.go, pkg/builders/catalogsourcebuilder.go, pkg/builders/deploymentbuilder.go, pkg/builders/rolebindingbuilder.go, pkg/builders/rolebuilder.go, pkg/builders/serviceaccountbuilder.go, pkg/builders/servicebuilder.go, pkg/catalogsourceconfig/configuring.go, pkg/catalogsourceconfig/deleted.go, pkg/grpccatalog/grpccatalog.go, pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/deleted.go, pkg/registry/registry.go, test/helpers/helpers.go, test/testsuites/csctargetnamespacetests.go, test/testsuites/opsrccreationtests.go, test/testsuites/opsrcdeletetests.go, test/testsuites/packagestests.go
Currently there is no way to determine the Kind that owns a given
resource the operator creates. This commit propagates information
about the Kind to the label creation function in the each resource
builder. It also update the deletion function to use these updated
labels as labelSelectors.
=> Bug 1723672: Fix owner labels to specify Kind

cmd/manager/main.go, deploy/operator.yaml, deploy/role.yaml, deploy/upstream/05_role.yaml, deploy/upstream/08_operator.yaml, manifests/05_role.yaml, manifests/10_operator.yaml, pkg/catalogsourceconfig/handler.go, pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go, pkg/controller/operatorsource/operatorsource_controller.go, pkg/operatorsource/handler.go, pkg/status/status.go, pkg/status/syncutils.go
Bug 1721537: Fix Degraded status on upgrade
Problem: There are three bugs that should be addressed within this bugzilla:
1. During an upgrade, multiple marketplace operators are running and updating the ClusterOperatorStatus at the same time, making it difficult to identify the actual state of the marketplace operator.
2. The marketplace operator is reporting degraded while it is upgrading. The marketplace operator reports degraded when the number of failed syncs surpases some threshold of total syncs. The marketplace operator currently reports a failed sync whenever an error is encountered while reconciling an operand (OperatorSources or CatalogSourceConfigs). This allows network issues or invalid operands to drive the marketplace operator to a degraded state.
3. It is difficult to …
=> Bug 1721537: Fix degraded status on upgrade

test/testsuites/packagestests.go
Problem: One of the e2e tests create a CatalogSourceConfig in the openshift-marketplace namespace. This breaks e2e tests on vanilla kubernetes.
Solution: Replace the hardcoded namespace with the namespace that the e2e-tests are being ran in.
=> [e2e] Remove hardcoded namespace

pkg/status/status.go, test/testsuites/clusteroperatorstatustests.go
Problem: The Marketplace ClusterOperator currently does not report
the Upgradeable ClusterOperatorStatus condition.
Solution: When the Marketplace Operator is Progressing, report
Upgradeable as false. In all other cases, report Upgradeable as true.
=> Bug 1727023: [status] Add upgradeable condition

pkg/operatorsource/configuring_test.go, pkg/registry/registry.go, test/testsuites/opsrccreationtests.go
**Problem**
Customers would like to add nodeSelectors to the registry pods. However we replace the pod template spec in the registry deployment on updates causing such additions to be lost.
**Solution**
Instead of replacing the pod template spec only update the required fields like command service accounts.
=> Bug 1696726: Don't replace pod spec on updates

pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go, pkg/controller/operatorsource/operatorsource_controller.go, pkg/operatorsource/factory.go, pkg/operatorsource/succeeded.go, pkg/watches/helpers.go, pkg/watches/opsrc_mapper.go, test/testsuites/watchtests.go
Watch for deletion of CatalogSources, Deployments, Services, ServiceAccounts, Roles and RoleBindings and recreate them if they belong to a OperatorSource.
- Add a watch that uses EnqueueRequestsFromMapFunc with a predicate that filters out non-deletion events
- Deletion predicate function only returns true if the event belongs to a child resource
- Add a mapper function that figures out the reconciliation request given the resource being deleted
- Make newReconciler return *ReconcileOperatorSource to allow the mapper to have access to the client
- Update the succeeded reconciler to check if the child resources have been deleted and set the phase to configuring if it has
=> [opsrc] Add watches for deletion of child resources

pkg/apis/operators/v1/operatorsource_types.go
IsEqual() was ignoring AuthorizationToken, Publisher and SecretName. This PR fixes that.
=> [opsrc] Fix IsEqual()

pkg/status/status.go, test/e2e/main_test.go, test/testgroups/clusteroperatortests.go, test/testsuites/clusteroperatorstatustests.go
Problem:
The must-gather tool is not able to gather enough information about the marketplace operator.
Solution:
The must-gather tool requires a field, RelatedObjects, in the ClusterOperator CR to be populated with ObjectReferences of the resources associated with the operator. This PR populates this field with the operator's namespace and the OperatorSource/CatalogSourceConfig/CatalogSource resources in the same namespace.
Reason for inclusion in 4.1.z:
Without having the RelatedObjects in the ClusterOperator CR, the CEE team will not be able to use the must-gather tool to collect information about the marketplace operator from customer. This makes it hard for them to provide engineering with enough information about issues found on production clusters. Having this fix in 4.1 will …
=> Bug 1717509: [status] Populate RelatedObjects

pkg/migrator/migrator.go, test/testgroups/migrationtests.go, test/testsuites/migrationtests.go
CatalogSourceConfigs that were not created by an OperatorSource or by
the UI as part of the 4.1 install flow are deleted on operator restart.
This is because a labelSelector was malformed and hence ignored. This
fixes that issue and adds a test case for this scenario.
=> Bug 1732760: Ensure cscs not deleted on operator restart

pkg/defaults/defaults.go, pkg/operatorsource/handler.go, test/testsuites/defaultopsrctests.go
Problem:
Currently, an issue exists where if a default opsrc is modified and that modification results in a reconciliation loop that puts the opsrc in a
failed state, it does not recover automatically.
Solution:
Rather than rely on the reconciliation loop to run erroneously on these opsrces and then returning them to their original state afterwards, add a filter to prevent updates to the spec that do not match the default. Do this by adding method to the defaults package `RestoreSpecIfDefault` that always overwrites the spec of any of the defaults to what is expected, and call that method at the beginning of the opsrc handler.
=> Bug 1732503: Restore default opsrc spec

pkg/catalogsourceconfig/registry.go
This should prevent the panic - `deployment` was being shadowed, and on timeout will be set to `nil`. This removes the shadowing so that the name comes from the non-nil `deployment` defined above.
I would typically add an e2e but I would need to rewrite a chunk of this to do that (otherwise the e2e test will always take 1+ minutes), and this section seems to have changed significantly between 4.1 and 4.2. But if anyone sees a convenient way to test this for 4.1, I'm all ears :)
=> Bug 1722096:  fix panic when scale down of registry deployment fails

build/build.sh
This change is required for building on other architectures.
=> Bug 1737175: Do not hardcode GOOS/GOARCH

cmd/manager/main.go, deploy/operator.yaml, deploy/role.yaml, deploy/upstream/05_role.yaml, deploy/upstream/08_operator.yaml, manifests/05_role.yaml, manifests/10_operator.yaml, pkg/catalogsourceconfig/handler.go, pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go, pkg/controller/operatorsource/operatorsource_controller.go, pkg/operatorsource/handler.go, pkg/status/status.go, pkg/status/syncutils.go
Bug 1740824: Fix Degraded status on upgrade
Problem: There are three bugs that should be addressed within this bugzilla:
During an upgrade, multiple marketplace operators are running and updating the ClusterOperatorStatus at the same time, making it difficult to identify the actual state of the marketplace operator.
The marketplace operator is reporting degraded while it is upgrading. The marketplace operator reports degraded when the number of failed syncs surpasses some threshold of total syncs. The marketplace operator currently reports a failed sync whenever an error is encountered while reconciling an operand (OperatorSources or CatalogSourceConfigs). This allows network issues or invalid operands to drive the marketplace operator to a degraded state.
It is difficult to identify why …
=> Bug 1740824: Fix degraded status on upgrade

pkg/migrator/migrator.go, test/helpers/helpers.go, test/testgroups/migrationtests.go, test/testsuites/migrationtests.go
Currently, the migration code (to move objects from 4.1 -> 4.2 by
removing the catalogsourceconfig from the install path of OLM) iterates
over each subscription and attempts find a valid catalog source to
associate it with. Right now however, there is logic to abort starting
the operator if there are errors finding an association during this
process.
This seems problematic, given that it is entirely possible that any
given subscription can be generated by the user and may be invalid.
Instead we should do a best effort to attempt to create this association
and in the case that we cannot find a suitable one we simply log a
warning and continue as usual.
Additionally, this pr fixes an issue where, in the case where the
subscription points to a specific catalog source config (through labels) …
=> Bug 1739562: [migration] Don't kill due to invalid subscription

deploy/operator.yaml, deploy/upstream/08_operator.yaml, manifests/08_operator.yaml, pkg/registry/registry.go
* Set container resource requests for operator deployment
* Set container resource requests for registry pod deployments
https://bugzilla.redhat.com/show_bug.cgi?id=1711070
=> Bug 1711070 - Set container resource requests

pkg/apis/operators/shared/shared.go, pkg/apis/operators/v1/operatorsource_types.go, pkg/controller/operatorsource/operatorsource_controller.go, pkg/defaults/defaults.go, pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/deleted.go, pkg/operatorsource/failed.go, pkg/operatorsource/handler.go, pkg/operatorsource/handler_test.go, pkg/operatorsource/initial.go, pkg/operatorsource/otherns.go, pkg/operatorsource/outofsync.go, pkg/operatorsource/purging.go, pkg/operatorsource/purging_test.go, pkg/operatorsource/reconciler.go, pkg/operatorsource/succeeded.go, pkg/operatorsource/validating.go, scripts/e2e-tests.sh, test/helpers/helpers.go, test/testsuites/defaultopsrctests.go
Problem:
An edge case bug was added when the default opsrc feature was added.
If a default opsrc was marked for deletion but the finalizer was
not removed by the operator before the operator restarted, then the
`defaults.EnsureAll()` method would attempt to create it. In that case,
the client would return an error and the operator would exit.
Solution:
When EnsureAll is called on startup, also ensure that there are no
finalizers still included on the operator source. If they are still
there, ignore it and allow the normal reconciliation cycle to take care
of deleting and recreating it.
Additionally, once the finalizer is removed at the end of the
reconciliation loop, wait for the opsrc to be cleaned up by the garbage
collector before recreating it. …
=> Bug 1732577: Handle delete events while operator is restarting

pkg/catalogsourceconfig/configuring.go, test/testsuites/csctargetnamespacetests.go, test/testsuites/packagestests.go
Problem:
If a CatalogSourceConfig specifies a source that does not exist the
CatalogSourceConfig will get stuck in the configuring phase. This error
is encountered because the Reconcile method for the CatalogSourceConfig
is not returning an error, causing the handler not to reconcile the
CatalogSourceConfig.
Solution:
Update the CatalogSourceConfig Configuring Reconcile method to return an
error. Also adds e2e tests to prevent regressions in the future.
=> Bug 1750654: The phase message of csc won't change when the env changed

CONTRIBUTING.md, README.md, docs/troubleshooting.md
The Dir of docs in OLM was changed from Documentation to doc. This change is to fix the broken links. 
- https://github.com/operator-framework/operator-sdk/issues/1887
=> Fix broken links - OLM Documentation was replaced by doc

deploy/service_monitor.yaml
The ServiceMonitor yaml defined in the deploy dir did not contain
required  RBAC permissions for the prometheus-k8s ServiceAccount.
This commit introduces the missing RBAC permissions.
=> [deploy] Sync deploy and manifest dirs

deploy/prometheus_rule.yaml, manifests/12_prometheus_rule.yaml
This commit introduces a change that renames the  marketplace rule
group from "./marketplace.rules" to  "marketplace.rules". This change
is meant to keep marketplace inline with the conventions followed by
other OpenShift operators.
=> Bug 1732164: Rename marketplace rules

pkg/operatorhub/operatorhub.go, pkg/status/status.go, test/testsuites/operatorhubtests.go
Problem:
The cluster operator status is never set to Available=True when
there are no default operator sources set. This is because it relies on
a set of reconciliations to return successfully and determines a ratio
based on that value. When no default operator sources are set, there are
no reconciliation events taking place and therefore the ratio is always
set to zero.
Solution:
When no default operator sources are set and no events are firing, set
the Available status to true.
https://bugzilla.redhat.com/show_bug.cgi?id=1757099
/cc @ecordell @kevinrizza
=> Bug 1757099: Assume available status is true without defaults

build/build.sh, cmd/manager/main.go, pkg/version/version.go
Add the `--version` option
It would be great if the  `marketplace-operator` binary can display the source commit info.
```console
sh-4.2$ marketplace-operator --help
INFO[0000] [metrics] Registering marketplace metrics    
INFO[0000] [metrics] Creating marketplace metrics RoundTripperFunc 
INFO[0000] [metrics] Serving marketplace metrics        
INFO[0000] Go Version: go1.12.8                         
INFO[0000] Go OS/Arch: linux/amd64                      
INFO[0000] operator-sdk Version: v0.8.0                 
Usage of marketplace-operator:
-defaultsDir string
the directory where the default OperatorSources are stored
-kubeconfig string
Paths to a kubeconfig. Only required if out-of-cluster.
-master string
The address of the …
```
=> add version option

deploy/prometheus_rule.yaml, manifests/12_prometheus_rule.yaml
This commit introduces a series of record rules that lump http status codes returned by Default AppRegistries into buckets of 100.
Solves #264
=> Bug 1768483: Limit Cardinality of Marketplace quay metrics

deploy/role.yaml, deploy/upstream/05_role.yaml, manifests/05_role.yaml, pkg/grpccatalog/grpccatalog.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/helper_test.go
Problem Statement:
Replicasets are being constantly generated when the `targetNamespace`
of a CatalogSourceConfig does not exist on the cluster.
The reconciliation loop relies on the controller's exponential backoff
so that events are not constantly reconciled. However, because the
`EnsureResources()` function recreates the registry service in order to
generate a new ip address before attempting to create the catalogsource,
the previous child resource watch constantly forces a reconciliation.
This causes the failing deployment to update constantly without ever
succeeding, and replicasets are continuously spawned.
Solution:
Ensure that the `targetNamespace` exists before attempting to recreate
the service. If the namespace does not exist, log an error and return.
This will prevent the …
=> Bug 1767547: Don't create invalid deployment

pkg/operatorhub/operatorhub.go, pkg/status/status.go, test/testsuites/operatorhubtests.go
Problem:
The cluster operator status is never set to Available=True when
there are no default operator sources set. This is because it relies on
a set of reconciliations to return successfully and determines a ratio
based on that value. When no default operator sources are set, there are
no reconciliation events taking place and therefore the ratio is always
set to zero.
Solution:
When no default operator sources are set and no events are firing, set
the Available status to true.
Cherry-picked from master branch
https://bugzilla.redhat.com/show_bug.cgi?id=1762006
=> Bug 1762006: Assume available status is true without defaults

pkg/registry/registry.go, pkg/registry/registry_test.go
Adds NodeSelector to all registry pods that ensures they will get scheduled to linux nodes only.
Bugs reporting different registry pods being scheduled to windows nodes in mixed clusters and failing to start
=> Bug 1775245: Schedule registry pods onto linux nodes only

build/build.sh
Problem:
In OpenShift clusters using Kuryr SDN a load balancer that does not
support UDP is required. In this case, Kuryr attempts to force disable
UDP on all pods by injecting a flag into the resolv.conf file of all
pods to force TCP use. However, this does not work in go programs
that have CGO disabled.
Solution:
Enable CGO and CGO_DEBUG
https://bugzilla.redhat.com/show_bug.cgi?id=1786037
=> Bug 1786037: Enable CGO in osbs build target

pkg/registry/registry.go
Problem:
Marketplace needs to support ipv6 clusters. Currently when creating
catalogsources, the marketplace points the catsrc to the clusterIP
address of the registry pod that it spins up. This cluster ip will not
work in an ipv6 only cluster.
Solution:
Use the dns address of the service to wire up the catalogsource to the
registry pod.
=> Use DNS for CatalogSource address

defaults/04_redhat_marketplace.yaml, test/testsuites/operatorhubtests.go
OLM-1441
This adds two new appregistry based operator sources.
This allows the open marketplace catalog built by the container pipeline to be a default catalog.
=> Add marketplace default catalog sources

manifests/05_role.yaml
This adds a new ClusterRole that can read the operatorhub config api, with appropriate labels to aggregate it to the cluster reader role. 
Users with cluster-reader should be able to view operatorhub config.
=> Bug 1796414: Add cluster role with aggregation for reading operatorhub config

pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go, pkg/controller/operatorsource/operatorsource_controller.go, pkg/status/status.go, test/helpers/helpers.go, test/testgroups/clusteroperatortests.go, test/testsuites/clusteroperatorstatustests.go, test/testsuites/operatorhubtests.go
In 4.5 we are deprecating the OperatorSource and CatalogSourceConfig APIs.
This PR introduces an alert in the logs, and also blocks upgrade to future
versions in presence of Opsrcs/CSCs by sending a Upgradeable: False message
to CVO.
=> Bug 1801294: Alert to make custom opsrc/csc users aware of deprecation

build/build.sh
Now, the output of the `marketplace-operator --version` is the sha of the commit in dist-git, not the source commit digest. This PR will fix this issue. 
```console
[jzhang@dhcp-140-36 ~]$ oc exec marketplace-operator-f7d7689c9-rllgk -- marketplace-operator --version
Marketplace source git commit: fb0762cf5b386d783527d036e4666b4468a12aad
time="2020-03-12T13:54:55Z" level=info msg="[metrics] Registering marketplace metrics"
time="2020-03-12T13:54:55Z" level=info msg="[metrics] Creating marketplace metrics RoundTripperFunc"
time="2020-03-12T13:54:55Z" level=info msg="[metrics] Serving marketplace metrics"
time="2020-03-12T13:54:55Z" level=info msg="Go Version: go1.13.4"
time="2020-03-12T13:54:55Z" level=info msg="Go OS/Arch: linux/amd64" …
```
=> show the source commit id

pkg/registry/registry.go, scripts/e2e-tests.sh
This increases the initial delay for the readiness and liveness probes for the appregistry pods. 
As more entries are added to appregistry, it takes longer to download them on startup. Since we are moving away from appregistry, we're mitigating the issue by increasing the startup time, rather than coming up with solutions that report ready faster.
Before merging, I would like to take a look at the ci cluster and ensure that the pods are not emitting events that signal an error for readiness probes.
=> Bug 1752063: increase initial delay for appregistry pods

README.md
The links to two of the CRD files were deprecated. So, this change is to update those links to the correct files
Correcting the documentation, so as to ease the reference for future readers or users
=> Updating the links to crd files

manifests/12_prometheus_rule.yaml, pkg/catalogsourceconfig/deleted.go, pkg/catalogsourceconfig/initial.go, pkg/metrics/metrics.go, pkg/operatorsource/deleted.go, pkg/operatorsource/initial.go
This PR introduces a Promethues alert to acompany the log and the
CVO status update in presence of a custom OperatorSource
or any CatalogSourceConfig.
=> [deprecation] Prometheus alert for custom resources

pkg/defaults/catsrcHelpers.go
This PR fixes the marketplace operator panic when the default
CatalogSource is configured without spec.updatestrategy.registry.interval
set.
=> Bug 1827676: Fix panic when default Catsrc polling is not set

cmd/manager/main.go, pkg/defaults/defaults.go
In #300, the OperatorHub API was enhanced to accept both OperatorSource
and CatalogSource as defaults. However, when an existing OperatorSource
in a cluster was switched to a CatalogSource, the old OperatorSource
persisted. This PR fixes the issue, and removes the obsolete OperatorSource,
so that there's only one source for a catalog of operators.
=> Bug 1831818: Remove Obsolete default OperatorSource

pkg/registry/registry.go
Check to ensure that the podtemplatespec associated with
the registry image matches the value passed in from the env
variable defined on the marketplace operator
=> Bug 1833207: Ensure correct registry image

pkg/catalogsourceconfig/initial.go, pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
This PR triggers a prometheus alert as soon as the
CSC reconclier is called, instead of waiting for the
CSC to reach the "Initial" phase.
=> Bug 1826372: Tigger alert for invalid CSC

pkg/status/status.go, test/testsuites/clusteroperatorstatustests.go
The Resource property in RelatedObjects field of ClusterServiceVersionStatus is meant to be the lowercase plural value, but were being populated with the Kind instead. Made modifications in this PR to switch all Kind values in Resource to the expected format.
=> Bug 1851213: Set Resource to plural in CSV RelatedObjects field

pkg/metrics/metrics.go, pkg/operatorsource/deleted.go, pkg/operatorsource/initial.go, pkg/status/status.go
Problem: It is possible for the marketplace operator to report that
deprecated CRs are present on cluster despite no CRs being present.
Solution: Marketplace already searches for non-default CRs on cluster
when reporting status. Marketplace will now use this search to report
the number of deprecated CRs on cluster.
=> Bug 1862481: Correctly count  non-default Marketplace CRs

defaults/03_community_operators.yaml
the location of the index has changed
The community operator image is no longer in quay.
=> Bug 1871987: Update 03_community_operators.yaml

Dockerfile.okd
Create a Dockerfile which builds marketplace operator for OKD payloads. 
It ensures Community operator index can be fetched by unauthenticated 
client (as OKD can be installed without a pull secret).
/cc @ecordell @shawn-hurley 
Later I'll create openshift/release PR to build it and promote to `origin` namespace so that it would land in OKD only
=> Bug 1874751: Add OKD-specific Dockerfile

cmd/manager/main.go, pkg/controller/add_catalogsource.go, pkg/controller/catalogsource/catalogsource_controller.go, test/helpers/helpers.go, test/testgroups/nosetuptests.go, test/testsuites/defaultcatsrctests.go
This PR implementes a watch for default CatalogSources, to recreate them
if they are deleted or edited.
=> Bug 1873250: Recreate default CatalogSources if deleted/edited

Dockerfile.okd
Openshift builds run as unprivileged user, so Dockerfile has to
switch to root explicitly to edit this file.
See error in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/11529/rehearse-11529-pull-ci-operator-framework-operator-marketplace-master-okd-images/1301135639957213184
/cc @kevinrizza @ecordell
=> Bug 1874751: Dockerfile.okd: switch to root user when updating manifests

Makefile, cmd/manager/main.go, pkg/operatorsource/configuring.go, pkg/operatorsource/configuring_test.go, pkg/operatorsource/factory.go, pkg/operatorsource/handler.go, pkg/operatorsource/poller.go, pkg/operatorsource/syncer.go
The syncing of remote app-registry was removed by #302 since it was
tied to the syncing of the child CatalogSourceConfig which was removed
in #302. This PR puts the syncing of remote app-registry back in, minus
the syncing of the non-existing child catalogSourceConfig.
=> Bug 1877564: Sync remote app-registry

pkg/registry/registry.go
Fixes community and certified operators pods crash looping because their startup time exceeds their readiness probe timeout. Increase that timeout from 30s to 60s.
=> Bug 1873546: Increase registry delay for large payloads

pkg/status/status.go
marketplace-operator install fails intermittently, with marketplace never setting its status as available.
Marketplace checks for a preexisting false available condition for making this update, which can 
incorrectly lead to the install getting stuck. Removing this wrapping condition to allow marketplace to
set its availability to true without this issue.
=> Bug 1885376: Remove condition around marketplace OperatorAvailable status update

pkg/catalogsourceconfig/deleted.go, pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go, pkg/metrics/metrics.go, pkg/operatorsource/deleted.go, pkg/operatorsource/initial.go, pkg/status/status.go
Problem: It is possible for the marketplace operator to report that
deprecated CRs are present on cluster despite no CRs being present.
Solution: Marketplace already searches for non-default CRs on cluster
when reporting status. Marketplace will now use this search to report
the number of deprecated CRs on cluster.
=> Bug 1872880: Correctly count  non-default Marketplace CRs

cmd/manager/main.go
Remove the unused const variable `resyncInterval`.
It's confusing for the users, see: https://bugzilla.redhat.com/show_bug.cgi?id=1888527 
=> remove the unused resyncInterval

pkg/status/status.go
Problem: The Marketplace operator should not report that it is in a bad state to Telemeter when it exits gracefully.
Solution: No longer report that the operator has exited when the operator shuts down gracefully.
=> Bug 1838352: Don't report OperatorExited to ClusterOperator

pkg/controller/catalogsource/catalogsource_controller.go, test/testsuites/defaultcatsrctests.go
With the introduction of #336, when a CatalogSource with the same name as that of a
default CatalogSource name was being created, the new CatalogSource was either being
restored to the default Spec, or being removed if the CatalogSource was disabled via
OperatorHub. This made is impossible to create a CatalogSource with the same name as
that of the default CatalogSource in a disconnected cluster enviroment. This PR fixes
the issue by allowing for creation/update/deleteion of a CatalogSource with the same
name as that of a default CatalogSource, if it has been disabled via OperatorHub first.
When the default CatalogSource is renabled via OperatorHub, the default CatalogSource
Spec is restored by overriding the custom created CatalogSource.
**Reviewer …
=> Bug 1868770: Allow catsrc with default catsrc name in disconnected env

pkg/status/status.go
Problem: Marketplace does not always report the degraded
ClusterStatusConditionType when it is reporting its status to CVO.
Solution: Marketplace should report when it is degraded and ensure that
the degraded condition is present.
=> Bug 1896160: Marketplace should report when it is degraded

deploy/upstream/08_operator.yaml
Problem: The `registryServerImage` runtime argument was recently removed
from marketplace but the marketplace deployment defined for the upstream
build did not remove the argument which caused the upstream marketplace
pod to crash.
Solution: Update the deployment manifest so it does not include the
`registryServerImage` runtime argument.
=> Fix upstream deployment

pkg/controller/catalogsource/catalogsource_controller.go, pkg/defaults/catsrcHelpers.go, pkg/defaults/defaults.go, test/helpers/helpers.go, test/testsuites/defaultcatsrctests.go, test/testsuites/operatorhubtests.go
Superseding #372.
In #362, marketplace's catalogsource reconciler was updated to allow
custom Catalogsources with the same name as one of the default
Catalogsources, when the default Catalogsource was disabled first with
the operatorhub api. However, when marketplace was restarted, the
custom catalogsource was being force deleted by marketplace's
operatorhub controller.
This PR adds a special annotation to the default CatalogSources, and
updates the operator to delete any catalogsource with the same name as
one of the default only if the CatalogSource has that special
annotation. In addition, the behavior of the marketplace operator as
it relates to reconciling the default CatalogSources should no longer
be tied to its process lifecycle.
=> Bug 1908431: Preserve custom catsrc w/ default catsrc name on restart

pkg/status/status.go
Problem: The Marketplace operator should not report that it is in a bad
state to Telemeter when it exits gracefully.
Solution: No longer report that the operator has exited when the
operator shuts down gracefully.
=> Bug 1909217: Do not report degraded when Marketplace exits gracefully

pkg/controller/catalogsource/catalogsource_controller.go, pkg/defaults/catsrcHelpers.go, pkg/defaults/defaults.go, test/helpers/helpers.go, test/testsuites/defaultcatsrctests.go, test/testsuites/operatorhubtests.go
In #362, marketplace's catalogsource reconciler was updated to allow
custom Catalogsources with the same name as one of the default
Catalogsources, when the default Catalogsource was disabled first with
the operatorhub api. However, when marketplace was restarted, the
custom catalogsource was being force deleted by marketplace's
operatorhub controller.
This PR adds a special annotation to the default CatalogSources, and
updates the operator to delete any catalogsource with the same name as
one of the default only if the CatalogSource has that special
annotation. In addition, the behavior of the marketplace operator as
it relates to reconciling the default CatalogSources should no longer
be tied to its process lifecycle.
=> Bug 1915905: Preserve custom catsrc w/ default catsrc name

defaults/03_community_operators.yaml
Changes community cagalog image reference
* from: `registry.redhat.io/redhat/community-operator-index:latest`
* to: `registry.redhat.io/redhat/community-operator-index:v4.6`
OpenShift clusters should pin to catalog images specific to their cluster version.
=> Bug 1937986: wrong community catalog image reference

manifests/01_namespace.yaml, manifests/04_service_account.yaml, manifests/05_role.yaml, manifests/06_role_binding.yaml, manifests/07_configmap.yaml, manifests/08_service.yaml, manifests/09_operator.yaml, manifests/10_clusteroperator.yaml, manifests/11_service_monitor.yaml
This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all operator-marketplace
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.
=> Annotate manifests for single-node-developer cluster profile

manifests/01_namespace.yaml, manifests/04_service_account.yaml, manifests/05_role.yaml, manifests/06_role_binding.yaml, manifests/07_configmap.yaml, manifests/08_service.yaml, manifests/09_operator.yaml, manifests/10_clusteroperator.yaml, manifests/11_service_monitor.yaml
Part 1 of ibm-cloud-managed profile support. 
Updates existing manifests by adding ibm-cloud-managed profile
annotations. Function is not affected.
This change allows the manifests for this operator to be included in an IBM cloud managed (ROKS) deployment of OpenShift.
=> Add ROKS profile annotation

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml, manifests/01_namespace.yaml, manifests/09_operator.yaml
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Note: The added CatalogSource annotations will not affect their
corresponding pods until after
https://github.com/operator-framework/operator-lifecycle-manager/pull/2085
is merged.
Adds the new OpenShift management workload annotations to all namespaces, pods, and CatalogSources.
These annotations will allow Kubelet and CRI-O to recognize "management" pods and allocate them to specific CPUs on resource-constrained systems, such as Single Node OpenShift. …
=> Add management workload annotations

manifests/09_operator-ibm-cloud-managed.yaml, scripts/update-manifests.sh
Adds a script that generates a version of the operator manifest specific for the ibm-cloud-managed profile.
The resulting manifest has an annotation for ibm-cloud-managed and has no node selector.
On IBM Cloud managed there are no master nodes, the control plane is externally managed. Therefore operator deployments cannot have a nodeselector for master nodes. Support for 'cluster profiles' in the CVO makes it possible to target manifests to a specific profile by setting an annotation on the manifest for the profile to which it belongs. This PR creates a version of the marketplace operator deployment that does not have a master node selector that will only be applied when running under an 'ibm-cloud-managed' profile.
**Reviewer …
=> Bug 1949277: Add operator manifest specific to ibm-cloud-managed profile

scripts/e2e-tests.sh, scripts/run-e2e-job.sh
Update the e2e-job and e2e-tests bash scripts and fix the issue where
the /tmp/operator-sdk binary isn't in $PATH locally by adding the ability
to override the operator-sdk binary we're testing against.
Update the scripts/e2e-tests.sh script and export GO111MODULE=off now
that we're building and testing with Go 1.16, but we're still using dep
as the package manager.
=> Bug 1950417: Add the ability to override the operator-sdk binary in e2e tests

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml, manifests/09_operator.yaml
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Changing requirements.
/hold
Hold until after openshift/kubernetes#632 is merged please
=> Rename workload annotations

manifests/12_prometheus_rule.yaml
With the [introduction of the `catalogsource_ready` metric in olm](https://github.com/operator-framework/operator-lifecycle-manager/pull/2152), alerts can be
fired for the default CatalogSources marketplace deploys if they are in	a non-ready state.
This PR introduces prometheus alerts for any default CatalogSources that have
been in a Non-Ready state for more than 10 mins.
**See it in action:**
`CommunityOperatorsCatalogError` alert being fired on a deployment of marketplace with an intentional bad image for `community-operators`
=> Bug 1936585: Configure alerts for Non-Ready Default CatalogSources

manifests/12_prometheus_rule.yaml
Follow up for #402. This PR adds the annotations required by CVO to
communicate the intention of applying the manifest on ocp installation.
=> Bug 1936585: Add CVO specific annotations

Dockerfile.rhel7
Remove the defaultDir argument from the operator manifest on ARM.
﻿The defaults currently point to 4.8 indexes which do not yet exist on
ARM, which result in unnecessary alerts and the need for a post-install
command to silence them.  Removing the defaultDir argument from the
operator launch command on ARM should avoid this.
This should be reverted once 4.9 indexes are available.
=> Start without defaults on ARM

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
This priorityclass annotation will contain priorityclass setting
for registry pods that are associated with default catalogsources.
The selected priorityclass for registry pod is 'system-cluster-critical'.
Signed-off-by: Vu Dinh <vudinh@outlook.com>
=> Bug 1954869: Add priorityclass annotation to default catalogsources

Makefile, test/e2e/clusteroperator_test.go, test/e2e/operatorhub_test.go
Update the Makefile `e2e-job` target and add the --randomizeAllSpecs
ginkgo flag. This should help weed out any state flakes when tests are
run in completely random order.
Update relevant test/e2e test packages and fix flaky state behavior.
=> Makefile,test: Fix flaky e2e tests

manifests/06_role_binding.yaml
Cherry-pick of https://github.com/operator-framework/operator-marketplace/pull/390 on `release-4.7`, so that we could drop v1beta1 support in 4.7 CVO
=> Bug 1961341: [release-4.7] Update openshift rolebindings to v1

manifests/12_prometheus_rule.yaml
Adding a summary annotation and replace the message annotation with description for prometheus alerts.
Fixing Bug 1992510 which references the [Open Shift alerting standards](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#documentation-required).
=> Add summary and description for prometheus alerts

Dockerfile.rhel7
Reverts operator-framework/operator-marketplace#413
Depends on redhat-operator-index:v4.9 being available for arm64/aarch64:
/hold
=> Bug 1996928: Revert "Start without defaults on ARM"

manifests/10_clusteroperator.yaml
ClusterOperator is cluster-scoped, [not namespaced][1].
I don't think this causes any issues though, so no bug, and we can land once we open for 4.9.
/hold
[1]: https://github.com/openshift/api/blob/e5fb810477d3f7e8c38e7c0d262f916c407576b8/config/v1/types_cluster_operator.go#L9
=> manifests/10_clusteroperator: Drop the unused namespace property

manifests/08_service.yaml, manifests/09_operator-ibm-cloud-managed.yaml
Looks like I missed adding the capabilities annotation to a few manifests.
=> Bug 2070792: chore(manifests): add missing capabilities annotation

Dockerfile, Dockerfile.okd, Dockerfile.rhel7
Copy the vendored OperatorHub CRD manifest from the openshift/api
during image builds. This will be the first step in transferring
ownership of the CRD from the cluster-config-operator to marketplace,
which will allow the CRD to be enabled and disabled as part of the
marketplace capability.
Signed-off-by: Nick Hale <njohnhale@gmail.com>
Related:
- [OLM-2542](https://issues.redhat.com/browse/OLM-2542)
- [BZ-2073288](https://bugzilla.redhat.com/show_bug.cgi?id=2073288)
cc @bparees @wking @perdasilva 
Supersedes #466
=> fix(capabilities): add operatorhub crd manifest

manifests/0000_03_marketplace-operator_02_operatorhub.cr.yaml
- Relocate the singleton OperatorHub CR instance from openshift/cluster-config-operator
- add the marketplace capability annotatation to CR instance
This consolidates ownership of OperatorHub-related manifests to the marketplace-operator
and will help prevent issues with resource application order.
Signed-off-by: Nick Hale <njohnhale@gmail.com>
=> fix(manifests): add singleton operatorhub cr

cmd/manager/main.go, pkg/status/status.go
Description of the change:
This PR updates the log level to reduce log spam. Also, adds log-level knob on binary to allow users to adjust verbose level of logger.
Motivation for the change:
Reduce log spamming with poll status updates. 
Reviewer Checklist
Implementation matches the proposed design, or proposal is updated to match implementation
* Sufficient unit test coverage
* Sufficient end-to-end test coverage
* Docs updated or added to /docs
* Commit messages sensible and descriptive
Signed-off-by: Jonathan Buchanan <jbuchananr19@gmail.com>
=> Bug 2057558: increase polling time of status report to reduce log spam

manifests/09_operator-ibm-cloud-managed.yaml, manifests/09_operator.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-marketplace/deployments/marketplace-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"marketplace-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capab
ilities (container \"marketplace-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"marketplace-operator\" must set securityContext.runAsNonRoot=true), …
```
=> manifests/deployment: comply to restricted pod security level

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
Signed-off-by: Jordan Keister <jordan@nimblewidget.com>
Bump catalog defaults to v4.11. 
v4.11 images now exist
=> Bug 2092464: shift marketplace operator catalogs default to v4.11

pkg/defaults/catsrcHelpers.go, test/e2e/operatorhub_test.go
Problem: Within the processCatsrc function a GET call is made to the
API for the catalogSource with a given namespace/name the error is
ignored if a 404 is returned. When defaultCatalogSources are disabled
and a new catalogSource named after one of the default catalogSources
exists it is possible for the previous 404 to be returned when no
error is encountered.
Fix: Do not allow the GET error to be returned at the end of the
processCatsrc function.
The error surfaces in the operatorHub status like so after the catalogSources are deleted:
```
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
name: cluster
spec:
disableAllDefaultSources: true
status:
sources:
- disabled: true
message: CatalogSource.operators.coreos.com "redhat-operators" not found
name: redhat-operators
status: …
```
=> Bug 2079610: Fix operatorHub status

manifests/01_namespace.yaml
Signed-off-by: perdasilva <perdasilva@redhat.com>
Adds psa annotations for the openshift-marketplace namespace to suppress PSA warnings in 4.11
=> Bug 2088541: Add psa anotations to namespace to suppress warnings

manifests/01_namespace.yaml
Add the label `pod-security.kubernetes.io/enforce: baseline` to the openshift manifests so that PSA enforcement doesn't cause catalog pods to fail to be scheduled.
=> Add PSA enforcement label

manifests/01_namespace.yaml
This PR removes the PSA baseline enforcement for workloads in the
openshift-marketplace namespace, so that the default restricted
profile can be enforced by default like other openshift-* namespaces.
This is possible due to the changes in
https://github.com/openshift/operator-framework-olm/pull/349
=> (namespace) remove PSA baseline enforcement

manifests/01_namespace.yaml
Pod Security Admission labels PR.
enforce restricted.
enforce-version: v1.24
Following instructions to set PSA enforce level for all `openshift-*` namespaces. 
=> (psa) make marketplace namespace restricted

Dockerfile.okd, hack/okd/0000_03_marketplace-operator_02_operatorhub.cr.yaml
Include custom OperatorHub manifest for OKD image
Since 4.11 OCP comes with OperatorHub definition which declares a capability
and enables all catalog sources. For OKD we want to enable just community-operators
as users may not have Red Hat pull secret set.
This commit would ensure that OKD version of marketplace operator gets
its own OperatorHub manifest with a custom set of operator catalogs enabled
=> OCPBUGS-441: Dockerfile.okd: include custom OperatorHub manifest

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml, manifests/01_namespace.yaml
OpenShift v4.12 had previously enforced PSA restrictions by defaults in and namespace prefixed with `openshift-`. This change has been delayed until OpenShift v4.13 and users should be allowed to run catalogs without restricted permissions in the openshift-marketplace namespace.
=> OCPBUGS-4758: Unenforce PSA Restrictions

manifests/01_namespace.yaml
The openshift-marketplace namespace will not be enforcing PSA restricted mode in the foreseeable future, and so we will be disabling the PSA audit and warnings.
=> OCPBUGS-5423: Remove PSA audit and warnings

manifests/01_namespace.yaml
The openshift-marketplace namespace will not be enforcing PSA restricted mode in the foreseeable future, and so we will be disabling the PSA audit and warnings.
=> [release-4.12] OCPBUGS-5468: Remove PSA audit and warnings

pkg/defaults/catsrcHelpers.go, test/e2e/operatorhub_test.go
**Problem:**
The `defaults` pkg for CatalogSources contains a helper func to check equality of two CatalogSources. It makes case-insensitive comparisons of a few fields and checks some others as well, but it doesn't perform a full diff. This results in some changes to the spec not being detected, resulting in the default fields not being maintained if changed by a user.
**Solution:**
Perform a full `reflect.DeepEqual` comparison of the two CatalogSourceSpecs, while still maintaining backwards-compatibility for the case-insensitive fields by `DeepCopy`ing both specs and setting those fields to lower-case.
OCPBUGS-5466
=> OCPBUGS-5466: Default CatalogSource aren't always reverted to default settings

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/04_redhat_marketplace.yaml
Update the image tag for all default CatalogSource images except the community operators index (pending ISV-3506)
Part 1 of a split of #511
=> OCPBUGS-10926: update image tag to 4.13 for all but community operators

defaults/03_community_operators.yaml
Updates only the community operator index image tag to 4.13.
Part 2 of splitting #511 (Part 1 in #513)
=> OCPBUGS-12794: update community index to 4.13 tag

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/04_redhat_marketplace.yaml
Description of the change:
Update the image tag for all default CatalogSource images except the community operators index (pending ISV-3664)
=> OCPBUGS-13921: Update image tag to 4.14 for all but community operators

defaults/03_community_operators.yaml
- Updates the community operator index image to use the 4.14 tag
- [OCPBUGS-13910](https://issues.redhat.com/browse/OCPBUGS-13910)
=> OCPBUGS-13910: update community-operator-index to 4.14 tag

manifests/09_operator.yaml
We do basically nothing in this controller - we watch an extremely small set of objects and make very few allocations past our informer queues. We should not be using much memory, ever.
=>  OCPBUGS-17157: manifests: tune memory use

manifests/05_role.yaml
Problem: The Marketplace Operator historically was responsible for making content available on cluster and serving it through pods. The Marketplace Operator has since evolved to simply manage the state of default catalogSource CRs based on specifications in the OperatorHub resource.
Solution: Remove any RBAC that is no longer necessary for the Marketplace Operator to serve its purpose.
=> OCPBUGS-15158: Scope Marketplace Operator RBAC

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/04_redhat_marketplace.yaml
Description of the change:
Update the image tag for all default CatalogSource images except the community operators index
Motivation for the change:
https://issues.redhat.com/browse/OCPBUGS-19710
=> OCPBUGS-19710: Update image tag to 4.15 for all but community operators

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/04_redhat_marketplace.yaml
Update the image tag for all default CatalogSource images except the community operators index
Update to latest images
=> OPECO-3029:  Update image tag to 4.16 for all indexes except community-operators

manifests/09_operator.yaml
this makes debugging via the API much easier by including the last few kb of the sysout for the container if the container crashes.
/assign @joelanford
=> OCPBUGS-28230: enforce termination message policy on all platform pods

manifests/09_operator-ibm-cloud-managed.yaml, manifests/09_operator.yaml
This PR explicitly sets the required SCC to be used to admit pods of the `marketplace-operator` deployments. The SCC chosen is the one that the pods are already getting admitted with, which means that this brings no change to the SCC used.
In some cases, custom SCCs can have higher priority than default SCCs, which means that they will be chosen over the default ones. This can lead to unexpected results; in order to protect openshift workloads from this, we must explicitly pin the required SCC to all our workloads in order to make sure that the expected one will be used.
=> AUTH-482: set required-scc for openshift workloads

manifests/09_operator-ibm-cloud-managed.yaml, manifests/09_operator.yaml
Cherry-pick of #561 
[OCPBUGS-37524](https://issues.redhat.com/browse/OCPBUGS-37524)
This PR explicitly sets the required SCC to be used to admit pods of the `marketplace-operator` deployments. The SCC chosen is the one that the pods are already getting admitted with, which means that this brings no change to the SCC used.
In some cases, custom SCCs can have higher priority than default SCCs, which means that they will be chosen over the default ones. This can lead to unexpected results; in order to protect openshift workloads from this, we must explicitly pin the required SCC to all our workloads in order to make sure that the expected one will be used.
=> [release-4.15] OCPBUGS-37524: Set required-scc for openshift workloads

.ci-operator.yaml, Dockerfile, Dockerfile.okd, go.mod
Updating marketplace-operator-container image to be consistent with ART for 4.17
__TLDR__:
Product builds by ART can be configured for different base and builder images than corresponding CI
builds. This automated PR requests a change to CI configuration to align with ART's configuration;
please take steps to merge it quickly or contact ART to coordinate changes.
The configuration in the following ART component metadata is driving this alignment request:
[marketplace-operator.yml](https://github.com/openshift/ocp-build-data/tree/6667e851f3657f1741e34eb6c38f05f53531664b/images/marketplace-operator.yml).
__Detail__:
This repository is out of sync with the downstream product builds for this component. The CI
configuration for at least one image differs from ART's expected product …
=> OCPBUGS-34244: Updating marketplace-operator-container image to be consistent with ART for 4.17

manifests/11_service_monitor.yaml
Add client certificate and key to service monitor so that prometheus scraper does not depend on API server availability.
https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md
=> NO-ISSUE: Add client certificate and key to service monitor

.github/dependabot.yml
Update dependabot configuration to group k8s and go library PRs
=> NO-ISSUE: Add dependabot k8s and go library groupings

config/networkpolicy/default-deny.yaml, config/networkpolicy/kustomization.yaml, config/networkpolicy/marketplace-operator.yaml, config/networkpolicy/unpack-bundles.yaml
=> OPRUN-3902: Add static NetworkPolicy for marketplace-operator

test/e2e/operatorhub_test.go
Increase default timeout.
Try to fix https://github.com/operator-framework/operator-marketplace/pull/664#issuecomment-3317267891 
Not only 4.16, but also the master, see: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/operator-framework_operator-marketplace/661/pull-ci-operator-framework-operator-marketplace-master-e2e-gcp-operator/1969926155641294848/artifacts/e2e-gcp-operator/test/build-log.txt
=> OCPBUGS-62132: Remove Expect func so that the test case can use the retry logic
