operator-framework/operator-marketplace

README.md, deploy/marketplace-pull-secret.yaml
Updated README to include steps to deploy the operator.
=> Update readme and remove pull secret

Dockerfile, tmp/build/Dockerfile
-Use openshift/origin-base when building image
=> Update Dockerfile base image

Makefile
-Update the make unit call to get mockgen dependency
-Pull down the mockgen repo before installing
=> Get all dependencies for unit tests

deploy/rbac.yaml
Tighten the RBAC policy restricting the operator to only the resources
it requires and nothing more.
=> Update RBAC policy

README.md
Thought we could use a section to explain the flow of the operator (even if subject to change in the future). Also including a description of how to deploy marketplace using OLM (for when @awgreene merges the CSV).
Let me know if you think this is needed - happy to change the wording, style etc.
=> Updating README to include flow description and deploy using OLM

pkg/catalogsourceconfig/factory.go, pkg/catalogsourceconfig/handler.go, pkg/catalogsourceconfig/initial.go
- Remove global log variable
- Fix initial reconciler documentation
=> Misc fixes

pkg/datastore/datastore.go, pkg/operatorsource/operatorsource.go
-Remove New() memoryDatastore method
-Initialize datastore in init() func
=> Make MemoryDatastore a Singleton

README.md, deploy/csv/marketplace.csv.yaml
Create a csv for the marketplace operator.
=> Add marketplace csv

deploy/catalogsourceconfig.crd.yaml, deploy/operatorsource.crd.yaml, pkg/apis/marketplace/v1alpha1/phase_types.go
Add
- Annotations
- Short name
- Additional printer columns
- Open API V3 Schema validation
=> Improve crds

Dockerfile.rhel7, build/Dockerfile
-Use openshift ci registry for base images
-Add downstream ocp dockerfile
=> Update dockerfiles for osbs

Gopkg.lock
-Dep ensure with dep v0.5.0
-Replaces inputs digest with input imports
=> Update gopkg using latest version of dep

OWNERS
As I am not actively participating in any of the market place code related activities, I am removing myself from the OWNERS file. Please feel free to tag me on PRs, in case I can be of any help.
/cc @aravindhp @tkashem
=> Remove ravi from market place reviewers

OWNERS
-Update OWNERS file to include krizza in list of reviewers
=> Add krizza to reviewers list

README.md
Add the order of installation of the artifacts to the `README.md` and
include new artifacts generated by @kevinrizza after upgrading 
Marketplace to version 0.1.1 of the Operator SDK.
=> [docs] Update README installation instructions

README.md, deploy/marketplace.ns.yaml
- Add a namespace yaml for creating the `openshift-marketplace` namespace
- Update the README's deploying section to reflect this
=> [deploy] Add namespace yaml

Dockerfile.rhel7
-Point to new build/ folder replacing tmp/ folder
-Match changes made to root dockerfile
=> Fix path issue for downstream repo

Makefile, scripts/run-e2e-job.sh
-Add script to configure and run e2e tests for ci
-Add e2e-ci-job target to Makefile
=> Add run-e2e-job script

Makefile, scripts/run-e2e-job.sh
-Update makefile task to match ci release job
-Rename task from e2e-ci-job to e2e-job
=> Run e2e-ci job

docs/how-to-upload-artifact.md, docs/marketplace-required-csv-annotations.md
Document what information marketplace expects to find within
an operator's csv.
=> [docs] Document operator metadata displayed in the marketplace UI

README.md, deploy/examples/catalogsourceconfig.cr.yaml, deploy/examples/operatorsource.cr.yaml
- Improve the operator and CRD descriptions
- Add CLI flow
- Fixup example CRs
=> [docs] Improve descriptions and add CLI instructions

README.md
As title, fix some errors links in the README.
=> Fix some doc links

pkg/catalogsourceconfig/configuring.go
-Throw error when csc spec references any package missing from datastore
-Set custom error on status and retry
-Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1679405
=> [csc] Handle invalid packages

pkg/catalogsourceconfig/registry.go
When there are update present in the Quay namespace but no new packages are being added or removed, the updates are not getting pulled down. This was due to the deployment spec for the registry pod being updated only when the list of packages changes. This PR fixes that issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1678906
=> Fix update sync with Quay

README.md, deploy/examples/catalogsourceconfig.cr.yaml, deploy/examples/community.operatorsource.cr.yaml, deploy/examples/upstream.operatorsource.cr.yaml
Use upstream-community-operators OperatorSource for installation on k8s.
=> Update README with newly created OperatorSource

deploy/role.yaml, deploy/upstream/05_role.yaml
-Update the cluster role yaml to match ownerref change for cvo manifest
=> Fix upstream and sdk cluster role

CONTRIBUTING.md, examples/cvo.override.yaml
Include instructions for setting up a dev environment,
conventions on commit message formatting, and other 
resources to help get contributions into marketplace-operator.
=> [docs] Add CONTRIBUTING.md

cmd/manager/main.go, deploy/operator.yaml, manifests/10_operator.yaml, manifests/11_clusteroperator.yaml, pkg/status/status.go, version/version.go
* Version is accepted as an environment variable within the CSV.
* Improved information provided by clusterOperator Conditions.
=> Bug 1686121: Update Marketplace management of clusterOperator conditions

README.md
=> [docs] Add CLI uninstall flow to README.md

pkg/catalogsourceconfig/update.go
Problem:
When the service restarts, we lose all cached knowledge about the
catalogsourceconfig, including the old targetNamespace. This is an
issue, because if the targetNamespace changed we want to remove the
catalogsource in the old targetNamespace and replace it with a new one.
Now that we are always assuming the cache is invalid if it is empty
(which is a valid assumption), we still don't have a way of cleaning up
old targetNamespace if it changed. Right now though, we will return an
error and not attempt to reconcile the CSC.
Not only that, but this error would also cause the catalogsourceconfig
to get into a stuck state. When the error was returned, we moved back
into the current state to retry. If the state was `success` or `failure`
the `catalogsourceconfig` would simply loop in …
=> Bug 1691241 [csc] Prevent getting stuck in current state when cache is invalid for csc

test/e2e/csc_tests.go, test/e2e/helpers.go, test/e2e/marketplace_test.go
Implement a test that:
* Creates a CatalogSourceConfig with non-existent targetNamespace
* Ensures that the status is not succeeded
* Creates the targetNamespace
* Ensures that the status is succeeded
Create a testutils file that contains methods used by various tests
=> [e2e] Test CSC with non-existant targetNamespace

README.md
=> [docs] Fix links for OperatorSource and CatalogSourceConfig

pkg/catalogsourceconfig/registry.go
In the case where a CatalogSourceConfig had packages from two different app registries, the generated command was getting mangled by the time it to got to the registry pod. This was fixed creating a list of -r options that was then passed to the registry pod.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1693375
=> Bug 1693375: [csc] Fix operator-registry command

docs/marketplace-required-csv-annotations.md
Merge required field content from 
https://github.com/operator-framework/community-operators/blob/master/docs/required-fields.md#required-fields-for-operatorhubio
=> [docs] consolidating required fields for embedded and io

deploy/crds/operators_v1_catalogsourceconfig_crd.yaml, deploy/crds/operators_v1_operatorsource_crd.yaml, deploy/role_binding.yaml, deploy/upstream/02_catalogsourceconfig.crd.yaml, deploy/upstream/03_operatorsource.crd.yaml, deploy/upstream/06_role_binding.yaml, manifests/02_catalogsourceconfig.crd.yaml, manifests/03_operatorsource.crd.yaml, manifests/06_role_binding.yaml
- Fix opsrc and csc schema validation error
- Remove unknown field from RoleRef (fixes #142)
https://bugzilla.redhat.com/show_bug.cgi?id=1688540
=> Bug 1688540: address validation errors

cmd/manager/main.go
Problem:
The routine responsible for ClusterOperator status reporting is stopped when the monitorStopCh is closed. The monitorStopCh is only closed when the stopCh is closed and is not used for any other purposes.
Solution:
Rather than creating a channel that is closed when the stopCh channel is closed, we can simply wait for the stopCh channel to close.
=> [status] Rely on stopCh to stop reporting status 

docs/e2e-testing.md, test/testgroups/operatorsourcetests.go, test/testsuites/csctargetnamespacetests.go, test/testsuites/invalidopsrctests.go, test/testsuites/opsrccreationtests.go
Use asserts/require instead of error checks
=> [e2e] Use asserts/require instead of error checks

docs/troubleshooting.md
* Fixes minor errors in the troubleshooting doc.
* Added section about Operators not showing up in UI
due to operator parsing error.
=> [docs] Fix troubleshooting doc

OWNERS
* Remove tkashem from approvers list
* Add kevinrizza to approvers list
=> Update approvers list in OWNERS file

test/testsuites/cscpackagetests.go
This updates the e2e package test based on the new error reporting
format that uses require/assert.
=> [e2e] Update error reporting for e2e pkg tests

pkg/status/status.go
Problem:
Marketplace recently encountered a bug that was difficult to diagnose
due to ClusterOperator.Status.Messages being set to an empty strings
in multiple location. This bug would have been easier to diagnose
if the messages were set/unique.
Solution:
Make sure that ClusterOperator.Status.Messages are not empty strings.
=> [status] Ensure CO status messages are not empty

README.md
We no longer create CatalogSources during install and instead we
reference existing CatalogSources on the cluster. This commit fixes
the uninstall documentation to describe the new uninstall flow where
interacting with a CatalogSourceConfig is no longer needed because none
is created during install.
=> [docs] Update uninstall flow to exclude csc

pkg/registry/registry.go
**Problem** 
Currently the operator scales down and then scales up the registry deployment, to cause it to forcefuly relaunch the pod so that updates from Quay are always picked up even when packages are not added or removed. This causes issues when we pick up a bad update that results in a crash looping pod resulting in an invalid registry for the CatalogSource.
**Solution**
Rather scaling down and up the deployment, update an annotation in the pod template spec which will also force the update.
**Note:** This PR alone won't fix BZ1700100. A fix to the e2e test that doesn't fail it on crash looping pods in the openshift-marketplace namespace is required.
=> Bug 1700100: Stop scaling down registry deployment

pkg/registry/registry.go
Every operator registry pod is created with a label
"marketplace.catalogsourceconfig" even though it may be created by an
OperatorSource. This fixes this issue by gating on the kind before
assigning these labels to the operator registry pod.
=> Bug 1733454: Specify kind in op registry labels

pkg/catalogsourceconfig/registry.go
=> Bug 1732588: Stop scaling down registry deployment

test/testsuites/operatorhubtests.go
A race condition can occur in the `testDisableNonDefault()` test in
the `OperatorHubTests` test suite e2e tests where the test updates the
config object then immediately does a get without waiting for the config
object's controller to handle the update event. In some cases, this can
cause a test failure because the get returns the old object that is yet
to be updated.
This commit updates the test to poll against the object until the config
object has a chance to be updated before continuing with the test.
=> Race condition in config test

pkg/status/status.go
Typo is from 8d04b9ceb9 (#282).
=> pkg/status: Fix "DprecatedAPIsInUse" -> "DeprecatedAPIsInUse" typo

README.md
Description of the change:
Changing href link to point to correct subsection on the child page
Motivation for the change:
Document Review
=> Updating href link to navigate to correct subsection

OWNERS
=> Update OWNERS file with latest team owners

test/testsuites/operatorhubtests.go
Poll for a CatalogSource to be created after updating OperatorHub.
=> Bug 1881713: Poll for CatalogSources in operatorhub test

cmd/manager/main.go
Clean up service and deployments associated with old opsrcs.
=> Bug 1891993: clean up child resources for old opsrcs

pkg/controller/catalogsource/catalogsource_controller.go
=> Format logs info

pkg/status/status.go
On meeting the expected sync ratio of 0.3, the marketplace operator
was only setting the DEGRADED and PROGRESSING conditions. The
AVAILABLE and PROGRESSING conditions were not being set. This PR fixes
that issue.
=> Bug 1881542: Set all CO conditions on meeting expected sync ratio

manifests/01_namespace.yaml, manifests/04_service_account.yaml, manifests/05_role.yaml, manifests/06_role_binding.yaml, manifests/07_configmap.yaml, manifests/08_service.yaml, manifests/09_operator.yaml, manifests/10_clusteroperator.yaml, manifests/11_service_monitor.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
Update default catalogs to point to 4.7 images
=> Bug 1927393: update defaults to 4.7

Dockerfile.rhel7, Makefile, build/build.sh
=> Build with Go 1.16

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
Update default manifests to 4.8 tags
=> update defaults to 4.8

manifests/06_role_binding.yaml
=> Bug 1947794: Update openshift rolebindings to v1

pkg/status/status.go
Previously, the conditions for clusteroperator marketplace was set to
available:false, progressing:true, upgradable:true, degraded:false with the
message "Progressing towards release version..." on startup of the marketplace
operator. This was done because a test in the openshift/origin test suites checked
to make sure operators did not set their condition to available:true immediately
on startup. That test has however been removed.
This PR sets the conditions for clusteroperator marketplace to available:true,
progressing:false, degreaded:false and upgradable:true on startup instead of
waiting for a particular time period.
=> Bug 1946790: Update clusteroperator status conditions on startup

README.md
**Description of the change:** Removing deprecated links and section related to CatalogSourceConfig
**Motivation for the change:**  Improving docs
=> Removing deprecated links and section related to CatalogSourceConfig

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
=> Bug 1986139: update defaults to 4.9

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
Reverts operator-framework/operator-marketplace#474
=> Revert "Bug 2092464: shift marketplace operator catalogs default to v4.11"

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
Signed-off-by: Vu Dinh <vudinh@outlook.com>
=> Bug 2092464: Update default catalogsource to use 4.11 images

manifests/12_prometheus_rule.yaml
=> Bug 2010375: Clarify reason/steps to diagnose in *CatalogError prom alert

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
Signed-off-by: Alexander Greene <greene.al1991@gmail.com>
=> OCPBUGS-2223: Update Default CatalogSource Images to 4.12 tag

manifests/01_namespace.yaml
Add the PSA labels for audit-version and warn-version
OCPBUGS-4873
=> OCPBUGS-4873: Add audit-version and warn-version labels

cmd/manager/main.go
No longer create the default `CatalogSource`s before the controller manager has actually started and reconciled an `OperatorHub` CR. This makes the `ensureDefaults()` function unused and therefore I have removed it.
- What currently happens is that the default `CatalogSource`s are created even if the `OperatorHub` marks them as disabled and then when the `OperatorHub` CR is reconciled they are all removed. This presents a problem in disconnected clusters where the defaults are disabled and a `CatalogSource` with the same name as a default is already present on cluster. In this scenario, the operator-marketplace will take ownership of the same-named `CatalogSource` and remove it when the `OperatorHub` CR is reconciled. Making …
=> OCPBUGS-9357: remove a race condition

defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
Depends on https://github.com/openshift/operator-framework-olm/pull/531
=> OCPBUGS-17157: defaults: add memory targets to CatalogSources

defaults/03_community_operators.yaml
Update the image tag for the community operators index
=> Update image tag to 4.15 for community operators

CONTRIBUTING.md, DCO
=> synching dco policy across v0 repos

defaults/03_community_operators.yaml
Update the community operator index image tag to 4.16.
=> OPECO-3031: Update community index to 4.16

Dockerfile.okd, defaults/01_redhat_operators.cr.yaml, defaults/02_certified_operators.yaml, defaults/03_community_operators.yaml, defaults/04_redhat_marketplace.yaml
=> OPRUN-3536: Replace 4.17 image references with 4.18

manifests/01_namespace.yaml
=> OCPBUGS-52340: Ensure that PSA label is latest instead of pinning versions

.github/dependabot.yml
Add dependabot and workflow to run go mod tidy and vendor for the opened PRs
Help us to keep this project maintained
=> NO-ISSUE: Add dependabot to help keep the project maintained

defaults/03_community_operators.yaml
=> OPRUN-3835: Update to 4.19 community-operators catalog

OWNERS
=> NO-JIRA: OWNERS: Add camilamacedo86 and tmshort as approvers

OWNERS
=> NO-ISSUE: (cleanup): Update Owner Alias - remove inactive maintainers

go.mod
=> ART-13123: append .0 to go.mod version

manifests/13_networkpolicy_default-deny.yaml, manifests/14_networkpolicy_marketplace-operator.yaml, manifests/15_networkpolicy_unpack-bundles.yaml
=> OCPBUGS-60669: Add NetworkPolicy for hypershift
